{
  config,
  lib,
  ...
}: let
  inherit (lib) mkEnableOption mkIf;
in {
  options.my.shell.bash.enable = mkEnableOption "Bash config";

  config = mkIf config.my.shell.bash.enable {
    # This repo owns ~/.bashrc via `scripts/setup-links.sh` + `dotfiles/home/bashrc`.
    # Prevent Home Manager from trying to create/link its own ~/.bashrc.
    home.file.".bashrc".enable = false;

    # Write HM-generated bash init (shell hooks from programs.direnv,
    # programs.starship, etc.) to a known file that the custom bashrc sources.
    home.file.".config/bash/hm-bash-init.sh" = {
      text = ''
        # Auto-generated by Home Manager — do not edit.
        # Source: programs.bash.initExtra (aggregated from all HM modules).
        ${config.programs.bash.initExtra}
      '';
    };

    programs.bash = {
      enable = true;
      # Do NOT set initExtra here — leave it open for HM modules
      # (programs.direnv, programs.starship, etc.) to append their hooks.
      # The content is written to ~/.config/bash/hm-bash-init.sh above.

      profileExtra = ''
        # Load Home Manager session variables (PATH, locale, etc.)
        if [ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]; then
          . "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
        fi
      '';
    };
  };
}
