# VS Code user-specific settings
# Generated by: scripts_py/sync_vscode_settings.py
#
# This file contains settings that VS Code has modified at runtime.
# These are separate from the "structural" settings in default.nix.
#
# To regenerate this file, run:
#   ./scripts/sync-vscode-settings
{
  # User-specific VS Code settings that are not managed by home-manager
  userSettings = {
    "git.confirmSync" = false;
  };
}
