#!/usr/bin/env python3
"""
Sync VS Code settings from runtime to Nix configuration.

This script helps maintain a hybrid approach:
- Home-manager manages "structural" settings (paths, formatters, language servers)
- VS Code manages "preference" settings (UI, dialogs, "don't show again")

Run this script periodically to capture VS Code's runtime changes and
generate Nix configuration that can be merged into your vscode.nix.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from scripts_py.utils import repo_root_from_script_path, log_error, log_info


def get_vscode_settings_path() -> Path:
    """Get the path to VS Code's user settings.json."""
    home = Path.home()
    # VS Code stores settings in ~/.config/Code/User/settings.json
    settings_path = home / ".config" / "Code" / "User" / "settings.json"
    return settings_path


def read_json_file(path: Path) -> dict[str, Any]:
    """Read and parse a JSON file."""
    try:
        with path.open("r") as f:
            return json.load(f)
    except FileNotFoundError:
        return {}
    except json.JSONDecodeError as e:
        log_error(f"Failed to parse {path}: {e}", err=sys.stderr)
        return {}


def get_managed_keys() -> set[str]:
    """Return the set of settings keys that are managed by home-manager.
    
    These should NOT be synced back, as they are controlled declaratively.
    """
    return {
        "editor.formatOnSave",
        "[nix]",
        "nix.enableLanguageServer",
        "nix.serverPath",
        "nix.formatterPath",
        "nix.serverSettings",
    }


def get_user_settings() -> dict[str, Any]:
    """Get user-modified settings (excluding home-manager managed ones)."""
    settings_path = get_vscode_settings_path()
    
    if not settings_path.exists():
        log_info(f"VS Code settings file not found at {settings_path}", out=sys.stdout)
        return {}
    
    all_settings = read_json_file(settings_path)
    managed_keys = get_managed_keys()
    
    # Filter out managed settings
    user_settings = {
        key: value
        for key, value in all_settings.items()
        if key not in managed_keys
    }
    
    return user_settings


def format_nix_value(value: Any, indent: int = 2) -> str:
    """Convert a Python value to Nix syntax."""
    indent_str = " " * indent
    
    if isinstance(value, bool):
        return "true" if value else "false"
    elif isinstance(value, str):
        # Escape special characters in Nix strings
        escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        return f'"{escaped}"'
    elif isinstance(value, (int, float)):
        return str(value)
    elif isinstance(value, list):
        if not value:
            return "[]"
        items = "\n".join(f"{indent_str}  {format_nix_value(v, indent + 2)}" for v in value)
        return f"[\n{items}\n{indent_str}]"
    elif isinstance(value, dict):
        if not value:
            return "{}"
        items = "\n".join(
            f'{indent_str}  "{k}" = {format_nix_value(v, indent + 2)};'
            for k, v in value.items()
        )
        return f"{{\n{items}\n{indent_str}}}"
    elif value is None:
        return "null"
    else:
        return str(value)


def generate_nix_config(settings: dict[str, Any]) -> str:
    """Generate Nix configuration from settings dictionary."""
    if not settings:
        return "  # No user-specific settings detected\n  {}"
    
    lines = ["  {"]
    for key, value in sorted(settings.items()):
        nix_value = format_nix_value(value, indent=4)
        lines.append(f'    "{key}" = {nix_value};')
    lines.append("  }")
    
    return "\n".join(lines)


def main() -> int:
    """Main entry point."""
    try:
        repo_root = repo_root_from_script_path(Path(__file__))
    except FileNotFoundError as e:
        log_error(str(e), err=sys.stderr)
        return 1
    
    log_info("Scanning VS Code settings...", out=sys.stdout)
    user_settings = get_user_settings()
    
    if not user_settings:
        log_info("No user-specific settings found (or all are managed by home-manager)", out=sys.stdout)
        return 0
    
    log_info(f"Found {len(user_settings)} user-specific setting(s)", out=sys.stdout)
    
    # Generate Nix configuration
    nix_config = generate_nix_config(user_settings)
    
    # Write to a file in the repo (feature-colocated with the VS Code module)
    output_path = repo_root / "home" / "features" / "vscode" / "user-settings.nix"
    
    header = """# VS Code user-specific settings
# Generated by: scripts_py/sync_vscode_settings.py
#
# This file contains settings that VS Code has modified at runtime.
# These are separate from the "structural" settings in vscode.nix.
#
# To regenerate this file, run:
#   ./scripts/sync-vscode-settings

{
  # User-specific VS Code settings that are not managed by home-manager
  userSettings =
"""
    
    footer = ";\n}\n"
    
    content = header + nix_config + footer
    
    log_info(f"Writing Nix configuration to {output_path}", out=sys.stdout)
    output_path.write_text(content)
    
    log_info("✓ Done! You can now review and integrate the changes.", out=sys.stdout)
    log_info(f"  Review: cat {output_path}", out=sys.stdout)
    log_info(f"  Then update vscode.nix to import these settings", out=sys.stdout)
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
