from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from scripts_py.schemastore import CatalogSchema, choose_schema_for_file, normalize_posix
from scripts_py.utils import RepoMarkers, log_error, log_info, repo_root_from_script_path


def _load_index(index_path: Path) -> dict:
    return json.loads(index_path.read_text(encoding="utf-8"))


def _index_schemas(index: dict) -> list[CatalogSchema]:
    out: list[CatalogSchema] = []
    for url, entry in index.get("schemas", {}).items():
        out.append(
            CatalogSchema(
                name=str(entry.get("name") or url),
                url=str(entry.get("url") or url),
                description=(str(entry.get("description")) if entry.get("description") else None),
                file_match=tuple(str(p) for p in (entry.get("fileMatch") or ())),
            )
        )
    return out


def _relativize(repo_root: Path, filename: str) -> str:
    p = Path(filename)
    if p.is_absolute():
        try:
            return normalize_posix(str(p.resolve().relative_to(repo_root)))
        except ValueError:
            return normalize_posix(filename)
    return normalize_posix(filename)


def _run_check_jsonschema(*, schema_path: Path, instance_path: Path) -> int:
    proc = subprocess.run(
        [
            "check-jsonschema",
            "--default-filetype",
            "yaml",
            "--schemafile",
            str(schema_path),
            str(instance_path),
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
    )
    if proc.returncode != 0:
        sys.stdout.write(proc.stdout)
    return proc.returncode


def validate(
    *,
    repo_root: Path,
    index_path: Path,
    files: list[str],
    all_files: bool,
    out,
    err,
) -> int:
    if not index_path.exists():
        log_error(
            (
                f"Missing schema index: {index_path.relative_to(repo_root)} "
                "(run scripts/sync-schemastore-index)"
            ),
            err=err,
        )
        return 2

    index = _load_index(index_path)
    indexed_files: dict[str, str] = index.get("files", {})

    schemas = _index_schemas(index)

    if all_files:
        targets = sorted(indexed_files.keys())
    else:
        targets = [_relativize(repo_root, f) for f in files]

    failures = 0
    validated = 0
    skipped = 0

    for rel in targets:
        # Don't resolve symlinks here.
        #
        # In this repo, `.pre-commit-config.yaml` is generated by devenv and is a
        # symlink to a `/nix/store/...pre-commit-config.json` file. Resolving the
        # symlink changes the filename extension, which changes how
        # `check-jsonschema` auto-detects the instance file type.
        abs_path = repo_root / rel
        if not abs_path.exists():
            skipped += 1
            continue

        schema_url = indexed_files.get(rel)
        if not schema_url:
            chosen = choose_schema_for_file(rel, schemas)
            if chosen:
                schema_url = chosen[0].url

        if not schema_url:
            skipped += 1
            continue

        schema_entry = index.get("schemas", {}).get(schema_url)
        if not schema_entry:
            log_error(f"Index missing schema entry for {schema_url}", err=err)
            return 2

        local_path = schema_entry.get("localPath")
        if not local_path:
            log_error(f"Index missing localPath for schema {schema_url}", err=err)
            return 2

        schema_path = repo_root / local_path
        if not schema_path.exists():
            log_error(
                f"Missing vendored schema: {local_path} (run scripts/sync-schemastore-index)",
                err=err,
            )
            return 2

        rc = _run_check_jsonschema(schema_path=schema_path, instance_path=abs_path)
        if rc != 0:
            failures += 1
        else:
            validated += 1

    if failures:
        log_error(f"Schema validation failed for {failures} file(s)", err=err)
        return 1

    log_info(f"Schema validation OK ({validated} validated, {skipped} skipped)", out=out)
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate files against SchemaStore schemas")
    parser.add_argument(
        "--index",
        default="schemas/schemastore-index.json",
        help="Path to schema index JSON",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="Validate all indexed files (ignores positional filenames)",
    )
    parser.add_argument("files", nargs="*")

    args = parser.parse_args(argv)

    repo_root = repo_root_from_script_path(Path(__file__), markers=RepoMarkers())
    index_path = repo_root / args.index

    return validate(
        repo_root=repo_root,
        index_path=index_path,
        files=args.files,
        all_files=args.all,
        out=sys.stdout,
        err=sys.stderr,
    )


if __name__ == "__main__":
    raise SystemExit(main())
